### ISSUE TITLE
TypeError: Cannot read property 'reject' of undefined

### ISSUE THREAD

**Issue by adnanumar** [twilio/client-js-1.4-examples#6]
Hi,
I have been using twilio client for web project, its working great at managequick.com. However, i have faced issue with twilio api when made an android apk package with phonegap. 
In newly generated application, twilio ui is appearing but when i try to make call, it gives following error:

`{"stack":"TypeError: Cannot read property 'reject' of undefined\n    at Device.eval (eval at globalEval (https://managequick.com/Content/js/jquery-2.1.4.min.js:2:2538), <anonymous>:46:44)\n    at emitOne (https://media.twiliocdn.com/sdk/js/client/releases/1.4.35/twilio.min.js:55:140680)\n    at Device.emit (https://media.twiliocdn.com/sdk/js/client/releases/1.4.35/twilio.min.js:55:141986)\n    at Connection.<anonymous> (https://media.twiliocdn.com/sdk/js/client/releases/1.4.35/twilio.min.js:55:38859)\n    at Object.onceWrapper (https://media.twiliocdn.com/sdk/js/client/releases/1.4.35/twilio.min.js:55:143939)\n    at emitOne (https://media.twiliocdn.com/sdk/js/client/releases/1.4.35/twilio.min.js:55:140797)\n    at Connection.emit (https://media.twiliocdn.com/sdk/js/client/releases/1.4.35/twilio.min.js:55:141986)\n    at PeerConnection.Connection.mediaStream.onclose (https://media.twiliocdn.com/sdk/js/client/releases/1.4.35/twilio.min.js:55:17737)\n    at PeerConnection.close (https://media.twiliocdn.com/sdk/js/client/releases/1.4.35/twilio.min.js:55:91179)\n    at Connection._disconnect (https://media.twiliocdn.com/sdk/js/client/releases/1.4.35/twilio.min.js:55:25323)","message":"Cannot read property 'reject' of undefined","name":"TypeError","logData":{"msg":"unhandledrejection","errorMsg":"Cannot read property 'reject' of undefined"}}`

I cannot produce the cause of this error, can anyone please help me with this specific error case. I might be doing something wrong or if its an issue, please let me know. Thanks for your time.

**Comment by esinniobiwaquareeb** [comment]
Remove cordova-custom-plugin and any other plugin that's dependent on it, then remove android platform and add it to it again

**Comment by ansarikhurshid786** [comment]
@esinniobiwaquareeb thanks

**Comment by liberty-rowland** [comment]
Thanks for the help @esinniobiwaquareeb !
